### PR TITLE
jf/OCE-0.17-update

### PR DESCRIPTION
**Pull request by jf---**
compiles SMESH for OCE 0.17
passes all ctests's succesfully

### CODE REVIEW

**Comment by jf---** [comment]
travis is really out of date for smesh... its relying on apt-get rather than conda.
shall I have a stab at updating this @tpaviot ?

**Comment by tpaviot** [comment]
@jf--- yes please

**Comment by jf---** [comment]
@tpaviot , are you OK to merge this PR and then handle Travis?

all tests seem to pass except for ``testSTLBinary``  ->[ stack smashing detected ](http://stackoverflow.com/questions/10087804/how-to-debug-stack-smashing-detected) 

 that error isnt raised on osx, cool to see this detected by travis.

**Comment by tpaviot** [comment]
@jf--- the opposite would be better, osx compilation results are not currently available on travis

**Comment by jf---** [comment]
@tpaviot , uhm, these days getting travis support for OSX is possible... 
for instance, the [open motion planning lib](https://travis-ci.org/ompl/ompl) does have osx support.

possible we might have to knock on the door and ask nicely :sunglasses: 
i guess we should explore this option...

**Comment by jf---** [comment]
So the travis build doesnt complete due to issue an issue with VTK.
The thing I dont get is that by default building VTK is off:

```cmake
option_with_default(PYTHONOCC_WRAP_VTK "Compile OCE/VTK wrapper" OFF)
```

however, travis still builds the vtk wrapper... hmmm

**Pull request merged**
